#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DOTNET via script
#=================================================
ynh_script_progression "Installing dotnet SDK via bash script..."
ynh_setup_source --dest_dir="$install_dir" --source_id="dotnet"
pushd "$install_dir"
    chmod +x dotnet-install.sh
    ./dotnet-install.sh --channel 9.0
popd

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"
pushd "$install_dir/fediprofile/src/FediProfile"
    dotnet run
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="The open-source, federated alternative to Linktree" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
