#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DOTNET via apt
#=================================================
ynh_script_progression "Installing dotnet SDK via apt..."
# Get YunoHost version
yunohost_major_version=$(yunohost --version | cut -d. -f1)
# Map YunoHost version to Debian version
case "$yunohost_major_version" in
    11) debian_version=12 ;;
    12) debian_version=13 ;;
    *) debian_version=12 ;; # Default to Debian 12
esac

#Add Microsoft package signing key
wget https://packages.microsoft.com/config/debian/$debian_version/packages-microsoft-prod.deb -O packages-microsoft-prod.deb 2>&1
dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb
ynh_install_app_dependencies dotnet-sdk-9.0

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"
pushd "$install_dir/fediprofile/src/FediProfile"
    dotnet run
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="The open-source, federated alternative to Linktree" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
