#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE DOTNET via apt
#=================================================
ynh_script_progression "Restoring dotnet SDK via apt..."
# Get YunoHost version
yunohost_major_version=$(yunohost --version | cut -d. -f1)
# Map YunoHost version to Debian version
case "$yunohost_major_version" in
    11) debian_version=12 ;;
    12) debian_version=13 ;;
    *) debian_version=12 ;; # Default to Debian 12
esac

#Add Microsoft package signing key
wget https://packages.microsoft.com/config/debian/$debian_version/packages-microsoft-prod.deb -O packages-microsoft-prod.deb 2>&1
dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb
apt install -y dotnet-sdk-10.0

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

chown -R "$app:$app" "$data_dir"

#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

yunohost service add "$app" --description="The open-source, federated alternative to Linktree" --log="/var/log/$app/$app.log"

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/etc/cron.d/$app"
ynh_restore "/etc/$app/"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

### Typically you only have either $app or PHP-FPM but not both at the same time...
ynh_systemctl --service="$app" --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
